services:
  postgresql:
    image: 'postgres:latest'
    ports:
      - "5432:5432"
    expose:
      - 5432
    environment:
      - 'POSTGRES_DB='
      - 'POSTGRES_PASSWORD='
      - 'POSTGRES_USER='
    volumes:
      - ./data:/var/lib/postgres/data
    networks:
      - backend

networks:
  backend:

volumes:
  postgres:

