spring:
  application:
    name: vktest
  liquibase:
    change-log: classpath:/db/changelog/db.changelog-master.xml

springdoc:
  swagger-ui:
    path: /swagger-ui.html
    enabled: true
  api-docs:
    path: /api-docs